version: '2'
services:
  database:
    container_name: ibm-task-mongo-dev
    image: mongo
    ports:
      - '27000:27017'
    networks:
      - default
  api:
    container_name: ibm-task-api
    image: task-rest-api:v1
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      - DB_HOST=ibm-task-mongo-dev
      - DB_PORT=27017
      - DB_NAME=tasks_db
    networks:
      - default
networks:
  default:
    external:
      name: ibm-network