version: '2'
services:
  api:
    container_name: ibm-task-api
    image: task-rest-api:v1
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      - connection=mongodb://database:27000/local
    networks:
      - ibm-network
  database:
    container_name: ibm-task-mongo-dev
    image: mongo
    ports:
      - '27000:27017'
    networks:
      - ibm-network
networks:
  ibm-network:
    external: true